CLUSTAL 2.1 multiple sequence alignment


Rosalind_1101      TGCGTTGACG---TAA--AACTAGCCTGCTTTTCC--TCTTGCT--AACA-GCGCAACTG
Rosalind_5533      TGCGTTGCGG---TAA--AACTAGCCTGCTTTTCCC-TCTTGCTGTAACACGCGCAACTG
Rosalind_3139      TGCGTTGACGGTACGG--AACTAGCCTGCTTTTCC--TCTTGCT--AACACGCGCAACTG
Rosalind_5850      TGCGTTGACGG--TAA--AA-TAGCCTGCTTTTCGAATCTTGCT--AACACGCGCAACTG
Rosalind_6039      TGCGTTGACGG--TAA--AACTAGCCTGCTTTTCC--TCTTGCT--ACCACGCGCAACTG
Rosalind_8002      TGCGTTGACGG--TAA--AACTAGCCTGCTTTTCC--TCTTGCTAACACGCGCGAGACTG
Rosalind_4474      TGCGTTGACGGGAAAAGCAACTAGCCTGCTTTTCCT-CTTTGCTAACCACCGCGCAACTG
Rosalind_1667      TGCGTTGACGG--TAA--AACTAGCCTGCTTTTCC--TCTTGCT--AACACGCGCAACTG
Rosalind_9515      TGCGTTGAGG---TAA--AATAGCCTTGCTTTTCCT-GTGTGCT--AACCGCTGAGTCTG
                   *******  *        **    * ********      ****         *   ***

Rosalind_1101      ----CAG-TCACATGCG--GCACAGTTC--TC-CAC
Rosalind_5533      --GTCAG-TCACATGCG--GCACATTTC--TC-CAC
Rosalind_3139      --GTCACCTCACATGCG--GCACATTTC--TC-CAC
Rosalind_5850      --GTCAG-TCAC-TGCG--GCACATTTC--TC-CAC
Rosalind_6039      --GTCAG-TCACATGCGC-GCACATTTC--TC-CAC
Rosalind_8002      CAATCAG-TCACATGCCAGGCACATTTACGTC-CAC
Rosalind_4474      --GTCAG-TCACATGGGCACCACTTTCT--CC-CAC
Rosalind_1667      --GTCAG-TCACATGCG--GCACATTTCGGCC-CA-
Rosalind_9515      --GTCG--TCAGACTCGC-CTACAGTTGCCTAGCAC
                       *   ***          **  *       **